class Unit:
    def __init__(self, id: int):
        self.id = id
        self.symbol = ""
        self.description = ""
        if(2000 <= id <= 32767):
            self.__get_attr(1646)
        elif(32768<= id <= 65535):
            self.symbol = "Manufacturer specific"
            self.description = ""
        else:
            self.__get_attr(id)
    
    def __get_attr(self, id: int):
        try:
            attr = UNIT_ADAPTER[id]
            self.symbol = attr["symbol"]
            self.description = attr["desc"]
        except KeyError:
            pass
    
    def __str__(self) -> str:
        return f"{self.symbol} ({self.description})"


UNIT_ADAPTER = {
    1000: {"symbol": "K", "desc": "kelvin SI"},
    1001: {"symbol": "°C", "desc": "degree Celsius T/K = t/°C+273.15 DT = 1°C is equal to DT = 1K"},
    1002: {"symbol": "°F", "desc": "degree Fahrenheit T/K = (t/°F+459.67)/1.8"},
    1003: {"symbol": "°R", "desc": "degree Rankine T/K = (T/°R)/1.8"},
    1004: {"symbol": "rad", "desc": "radian = 1 m/m"},
    1005: {"symbol": "°", "desc": "degree = (p/180) rad"},
    1006: {"symbol": "'", "desc": "minute = (1/60)°"},
    1007: {"symbol": "''", "desc": "second = (1/60)’"},
    1008: {"symbol": "gon", "desc": "gon (or grade) = (p/200) rad"},
    1009: {"symbol": "r", "desc": "revolution = 2p rad"},
    1010: {"symbol": "m", "desc": "meter SI"},
    1011: {"symbol": "km", "desc": "kilometer = 1000.0 m"},
    1012: {"symbol": "cm", "desc": "centimeter = 0.01 m"},
    1013: {"symbol": "mm", "desc": "millimeter = 10-3 m"},
    1014: {"symbol": "μm", "desc": "micrometer = 10-6 m"},
    1015: {"symbol": "nm", "desc": "nanometer = 10-9 m"},
    1016: {"symbol": "pm", "desc": "picometer = 10-12 m"},
    1017: {"symbol": "Å", "desc": "angstrom = 10-10 m"},
    1018: {"symbol": "ft", "desc": "foot = 12 in"},
    1019: {"symbol": "in", "desc": "inch (international) = 0.0254 mm"},
    1020: {"symbol": "yd", "desc": "yard = 36 in"},
    1021: {"symbol": "mile", "desc": "mile = 1760 yd"},
    1022: {"symbol": "nautical mile", "desc": "nautical mile = 1852 m"},
    1023: {"symbol": "m2", "desc": "square meter"},
    1024: {"symbol": "km2", "desc": "square kilometer"},
    1025: {"symbol": "cm2", "desc": "square centimeter"},
    1026: {"symbol": "dm2", "desc": "square decimeter"},
    1027: {"symbol": "mm2", "desc": "square millimeter"},
    1028: {"symbol": "a", "desc": "are = 102 m2"},
    1029: {"symbol": "ha", "desc": "hectare = 104 m2"},
    1030: {"symbol": "in2", "desc": "square inch"},
    1031: {"symbol": "ft2", "desc": "square feet"},
    1032: {"symbol": "yd2", "desc": "square yard"},
    1033: {"symbol": "mile2", "desc": "square mile"},
    1034: {"symbol": "m3", "desc": "cubic meter"},
    1035: {"symbol": "dm3", "desc": "cubic decimeter"},
    1036: {"symbol": "cm3", "desc": "cubic centimeter"},
    1037: {"symbol": "mm3", "desc": "cubic millimeter"},
    1038: {"symbol": "L", "desc": "liter = 10-3 m3"},
    1039: {"symbol": "cl", "desc": "centiliter = 0.01 L"},
    1040: {"symbol": "ml", "desc": "milliliter = 0.001 L"},
    1041: {"symbol": "hl", "desc": "hectoliter = 100 L"},
    1042: {"symbol": "in3", "desc": "cubic inch"},
    1043: {"symbol": "ft3", "desc": "cubic foot"},
    1044: {"symbol": "yd3", "desc": "cubic yard"},
    1045: {"symbol": "mile3", "desc": "cubic mile"},
    1046: {"symbol": "pint", "desc": "pint (U.S. liquid) = (1/8) gal"},
    1047: {"symbol": "quart", "desc": "quart (U.S. liquid) = (1/4) gal"},
    1048: {"symbol": "gal", "desc": "gallon (U.S.) = 231 in3"},
    1049: {"symbol": "ImpGal", "desc": "gallon (Imperial) = 4.54609 L"},
    1050: {"symbol": "bushel", "desc": "bushel (U.S. dry) = 2150.42 in3"},
    1051: {"symbol": "bbl", "desc": "barrel (U.S. petroleum) = 42 gal"},
    1052: {"symbol": "bbl (liq)", "desc": "barrel (U.S. liquid) = 31.5 gal"},
    1053: {"symbol": "ft3 std.", "desc": "standard cubic foot"},
    1054: {"symbol": "s", "desc": "second SI"},
    1055: {"symbol": "ks", "desc": "kilosecond = 103 s"},
    1056: {"symbol": "ms", "desc": "millisecond = 10-3 s"},
    1057: {"symbol": "μs", "desc": "microsecond = 10-6 m"},
    1058: {"symbol": "min", "desc": "minute = 60 s"},
    1059: {"symbol": "h", "desc": "hour = 60 min"},
    1060: {"symbol": "d", "desc": "day = 24 h"},
    1061: {"symbol": "m/s", "desc": "meter per second"},
    1062: {"symbol": "mm/s", "desc": "millimeter per second"},
    1063: {"symbol": "m/h", "desc": "meter per hour"},
    1064: {"symbol": "km/h", "desc": "kilometer per hour"},
    1065: {"symbol": "knot", "desc": "nautical mile per hour = 1.852 km/h"},
    1066: {"symbol": "in/s", "desc": "inch per second"},
    1067: {"symbol": "ft/s", "desc": "foot per second"},
    1068: {"symbol": "yd/s", "desc": "yard per second"},
    1069: {"symbol": "in/min", "desc": "inch per minute"},
    1070: {"symbol": "ft/min", "desc": "foot per minute"},
    1071: {"symbol": "yd/min", "desc": "yard per minute"},
    1072: {"symbol": "in/h", "desc": "inch per hour"},
    1073: {"symbol": "ft/h", "desc": "foot per hour"},
    1074: {"symbol": "yd/h", "desc": "yard per hour"},
    1075: {"symbol": "mi/h", "desc": "mile per hour = 0.44704 m/s"},
    1076: {"symbol": "m/s2", "desc": "meter per second squared"},
    1077: {"symbol": "Hz", "desc": "hertz = 1 s-1"},
    1078: {"symbol": "THz", "desc": "terahertz = 1012 Hz"},
    1079: {"symbol": "GHz", "desc": "gigahertz = 109 Hz"},
    1080: {"symbol": "MHz", "desc": "megahertz = 106 Hz"},
    1081: {"symbol": "kHz", "desc": "kilohertz = 103 Hz"},
    1082: {"symbol": "1/s", "desc": "per second = 1 s-1"},
    1083: {"symbol": "1/min", "desc": "per minute = (1/60) s-1"},
    1084: {"symbol": "r/s", "desc": "revolution per second"},
    1085: {"symbol": "rpm", "desc": "revolution per minute"},
    1086: {"symbol": "rad/s", "desc": "radian per second"},
    1087: {"symbol": "1/s2", "desc": "per second squared"},
    1088: {"symbol": "kg", "desc": "kilogram SI"},
    1089: {"symbol": "g", "desc": "gram = 10-3 kg"},
    1090: {"symbol": "mg", "desc": "milligram = 10-6 kg"},
    1091: {"symbol": "Mg", "desc": "megagram = 103 kg"},
    1092: {"symbol": "t", "desc": "metric ton = 103 kg"},
    1093: {"symbol": "oz", "desc": "ounce (Avoirdupois) = 1/16 lb"},
    1094: {"symbol": "lb", "desc": "pound (Avoirdupois) = 0.45359237 kg"},
    1095: {"symbol": "STon", "desc": "short ton = 2000 lb"},
    1096: {"symbol": "LTon", "desc": "long ton = 2240 lb"},
    1097: {"symbol": "kg/m3", "desc": "kilogram per cubic meter"},
    1098: {"symbol": "Mg/m3", "desc": "megagram per cubic meter"},
    1099: {"symbol": "kg/dm3", "desc": "kilogram per cubic decimeter"},
    1100: {"symbol": "g/cm3", "desc": "gram per cubic centimeter"},
    1101: {"symbol": "g/m3", "desc": "gram per cubic meter"},
    1102: {"symbol": "t/m3", "desc": "metric ton per cubic meter"},
    1103: {"symbol": "kg/L", "desc": "kilogram per liter"},
    1104: {"symbol": "g/ml", "desc": "gram per milliliter"},
    1105: {"symbol": "g/L", "desc": "gram per liter"},
    1106: {"symbol": "lb/in3", "desc": "pound per cubic inch"},
    1107: {"symbol": "lb/ft3", "desc": "pound per cubic foot"},
    1108: {"symbol": "lb/gal", "desc": "pound per gallon (U.S.)"},
    1109: {"symbol": "STon/yd3", "desc": "short ton per cubic yard"},
    1110: {"symbol": "°Twad", "desc": "degree Twaddell"},
    1111: {"symbol": "°Baum (hv)", "desc": "degree Baume heavy"},
    1112: {"symbol": "°Baum (lt)", "desc": "degree Baume light"},
    1113: {"symbol": "°API", "desc": "degree API"},
    1114: {"symbol": "SGU", "desc": "specific gravity units"},
    1115: {"symbol": "kg/m", "desc": "kilogram per meter"},
    1116: {"symbol": "mg/m", "desc": "milligram per meter"},
    1117: {"symbol": "tex", "desc": "tex = 10-6 kg/m"},
    1118: {"symbol": "kg·m2", "desc": "kilogram square meter"},
    1119: {"symbol": "kg·m/s", "desc": "kilogram meter per second"},
    1120: {"symbol": "N", "desc": "newton = 1 kg·m/s2"},
    1121: {"symbol": "MN", "desc": "meganewton = 106 N"},
    1122: {"symbol": "kN", "desc": "kilonewton = 103 N"},
    1123: {"symbol": "mN", "desc": "millinewton = 10-3 N"},
    1124: {"symbol": "μN", "desc": "micronewton = 10-6 N"},
    1125: {"symbol": "kg·m2/s", "desc": "kilogram square meter per second"},
    1126: {"symbol": "N·m", "desc": "newton meter"},
    1127: {"symbol": "MN·m", "desc": "meganewton meter"},
    1128: {"symbol": "kN·m", "desc": "kilonewton meter"},
    1129: {"symbol": "mN·m", "desc": "millinewton meter"},
    1130: {"symbol": "Pa", "desc": "pascal = 1 N/m2"},
    1131: {"symbol": "GPa", "desc": "gigapascal = 109 PA"},
    1132: {"symbol": "MPa", "desc": "megapascal = 106 PA"},
    1133: {"symbol": "kPa", "desc": "kilopascal = 103 PA"},
    1134: {"symbol": "mPa", "desc": "millipascal = 10-3 PA"},
    1135: {"symbol": "μPa", "desc": "micropascal = 10-6 PA"},
    1136: {"symbol": "hPa", "desc": "hectopascal = 102 PA"},
    1137: {"symbol": "bar", "desc": "bar = 100 kPa"},
    1138: {"symbol": "mbar", "desc": "millibar = 1 hPa"},
    1139: {"symbol": "torr", "desc": "torr = (1/760) atm"},
    1140: {"symbol": "atm", "desc": "atmosphere = 101325.0 Pa"},
    1141: {"symbol": "psi", "desc": "pound-force per square inch = (0.45359237 · 9.80665 / 0.02542 ) Pa (unreferenced or differential pressure)"},
    1142: {"symbol": "psia", "desc": "pound-force per square inch absolute = (0.45359237 · 9.80665 / 0.02542 ) Pa (referenced to a vacuum)"},
    1143: {"symbol": "psig", "desc": "pound-force per square inch gauge = (0.45359237 · 9.80665 / 0.02542 ) Pa (referenced to atmosphere)"},
    1144: {"symbol": "gf/cm2", "desc": "gram-force per square centimeter = 98.0665 Pa"},
    1145: {"symbol": "kgf/cm2", "desc": "kilogram-force per square centimeter = 98066.5 Pa"},
    1146: {"symbol": "inH2O", "desc": "inch of water"},
    1147: {"symbol": "inH2O (4°C)", "desc": "inch of water at 4°C"},
    1148: {"symbol": "inH2O (68°F)", "desc": "inch of water at 68°F"},
    1149: {"symbol": "mmH2O", "desc": "millimeter of water"},
    1150: {"symbol": "mmH2O (4°C)", "desc": "millimeter of water at 4°C"},
    1151: {"symbol": "mmH2O (68°F)", "desc": "millimeter of water at 68°F"},
    1152: {"symbol": "ftH2O", "desc": "foot of water"},
    1153: {"symbol": "ftH2O (4°C)", "desc": "foot of water at 4°C"},
    1154: {"symbol": "ftH2O (68°F)", "desc": "foot of water at 68°F"},
    1155: {"symbol": "inHg", "desc": "inch of mercury"},
    1156: {"symbol": "inHg (0°C)", "desc": "inch of mercury at 0°C"},
    1157: {"symbol": "mmHg", "desc": "millimeter of mercury"},
    1158: {"symbol": "mmHg (0°C)", "desc": "millimeter of mercury at 0°C"},
    1159: {"symbol": "Pa·s", "desc": "pascal second"},
    1160: {"symbol": "m2/s", "desc": "square meter per second"},
    1161: {"symbol": "P", "desc": "poise = 0.1 Pa·s"},
    1162: {"symbol": "cP", "desc": "centipoise = 1 mPa·s"},
    1163: {"symbol": "St", "desc": "stokes = 10-4 m2/s"},
    1164: {"symbol": "cSt", "desc": "centistokes = 1 mm2/s"},
    1165: {"symbol": "N/m", "desc": "Newton per meter"},
    1166: {"symbol": "mN/m", "desc": "millinewton per meter"},
    1167: {"symbol": "J", "desc": "joule = 1 N·m"},
    1168: {"symbol": "EJ", "desc": "exajoules = 1018 J"},
    1169: {"symbol": "PJ", "desc": "petajoules = 1015 J"},
    1170: {"symbol": "TJ", "desc": "terajoules = 1012 J"},
    1171: {"symbol": "GJ", "desc": "gigajoules = 109 J"},
    1172: {"symbol": "MJ", "desc": "megajoules = 106 J"},
    1173: {"symbol": "kJ", "desc": "kilojoules = 103 J"},
    1174: {"symbol": "mJ", "desc": "millijoules = 10-3 J"},
    1175: {"symbol": "W·h", "desc": "watt hour"},
    1176: {"symbol": "TW·h", "desc": "terawatt hour"},
    1177: {"symbol": "GW·h", "desc": "gigawatt hour"},
    1178: {"symbol": "MW·h", "desc": "megawatt hour"},
    1179: {"symbol": "kW·h", "desc": "kilowatt hour"},
    1180: {"symbol": "calth", "desc": "calorie (thermochemical) = 4.184 J"},
    1181: {"symbol": "kcalth", "desc": "kilocalorie (thermochemical) = 4.184 kJ"},
    1182: {"symbol": "Mcalth", "desc": "megacalorie (thermochemical) = 4.184 MJ"},
    1183: {"symbol": "Btu_th", "desc": "British thermal unit (thermochemical) = (4184 · 0.45359237/1.8) J"},
    1184: {"symbol": "datherm", "desc": "dekatherm = 1.05506·109 J"},
    1185: {"symbol": "ft·lbf", "desc": "foot pound-force = 1.3558179483314004 J"},
    1186: {"symbol": "W", "desc": "watt = 1 J/s"},
    1187: {"symbol": "TW", "desc": "terawatt = 1012 W"},
    1188: {"symbol": "GW", "desc": "gigawatt = 109 W"},
    1189: {"symbol": "MW", "desc": "megawatt = 106 W"},
    1190: {"symbol": "kW", "desc": "kilowatt = 103 W"},
    1191: {"symbol": "mW", "desc": "milliwatt = 10-3 W"},
    1192: {"symbol": "μW", "desc": "microwatt = 10-6 W"},
    1193: {"symbol": "nW", "desc": "nanowatt = 10-9 W"},
    1194: {"symbol": "pW", "desc": "picowatt = 10-12 W"},
    1195: {"symbol": "Mcalth/h", "desc": "megacalorie per hour"},
    1196: {"symbol": "MJ/h", "desc": "megajoule per hour"},
    1197: {"symbol": "Btu_th/h", "desc": "British thermal unit per hour"},
    1198: {"symbol": "hp", "desc": "horsepower (electric) = 746 W"},
    1199: {"symbol": "W/(m·K)", "desc": "watt per meter kelvin"},
    1200: {"symbol": "W/(m2·K)", "desc": "watt per square meter kelvin"},
    1201: {"symbol": "m2·K/W", "desc": "square meter kelvin per watt"},
    1202: {"symbol": "J/K", "desc": "joule per kelvin"},
    1203: {"symbol": "kJ/K", "desc": "kilojoule per kelvin"},
    1204: {"symbol": "J/(kg·K)", "desc": "joule per kilogram kelvin"},
    1205: {"symbol": "kJ/(kg·K)", "desc": "kilojoule per kilogram kelvin"},
    1206: {"symbol": "J/kg", "desc": "joule per kilogram"},
    1207: {"symbol": "MJ/kg", "desc": "megajoule per kilogram"},
    1208: {"symbol": "kJ/kg", "desc": "kilojoule per kilogram"},
    1209: {"symbol": "A", "desc": "ampere SI"},
    1210: {"symbol": "kA", "desc": "kiloampere = 103 A"},
    1211: {"symbol": "mA", "desc": "milliampere = 10-3 A"},
    1212: {"symbol": "μA", "desc": "microampere = 10-6 A"},
    1213: {"symbol": "nA", "desc": "nanoampere = 10-9 A"},
    1214: {"symbol": "pA", "desc": "picoampere = 10-12 A"},
    1215: {"symbol": "C", "desc": "coulomb = 1 A·s"},
    1216: {"symbol": "MC", "desc": "megacoulomb = 106 C"},
    1217: {"symbol": "kC", "desc": "kilocoulomb = 103 C"},
    1218: {"symbol": "μC", "desc": "microcoulomb = 10-6 C"},
    1219: {"symbol": "nC", "desc": "nanocoulomb = 10-9 C"},
    1220: {"symbol": "pC", "desc": "picocoulomb = 10-12 C"},
    1221: {"symbol": "A·h", "desc": "ampere hour"},
    1222: {"symbol": "C/m3", "desc": "coulomb per cubic meter"},
    1223: {"symbol": "C/mm3", "desc": "coulomb per cubic millimeter"},
    1224: {"symbol": "C/cm3", "desc": "coulomb per cubic centimeter"},
    1225: {"symbol": "kC/m3", "desc": "kilocoulomb per cubic meter"},
    1226: {"symbol": "mC/m3", "desc": "millicoulomb per cubic meter"},
    1227: {"symbol": "μC/m3", "desc": "microcoulomb per cubic meter"},
    1228: {"symbol": "C/m2", "desc": "coulomb per square meter"},
    1229: {"symbol": "C/mm2", "desc": "coulomb per square millimeter"},
    1230: {"symbol": "C/cm2", "desc": "coulomb per square centimeter"},
    1231: {"symbol": "kC/m2", "desc": "kilocoulomb per square meter"},
    1232: {"symbol": "mC/m2", "desc": "millicoulomb per square meter"},
    1233: {"symbol": "μC/m2", "desc": "microcoulomb per square meter"},
    1234: {"symbol": "V/m", "desc": "volt per meter"},
    1235: {"symbol": "MV/m", "desc": "megavolt per meter"},
    1236: {"symbol": "kV/m", "desc": "kilovolt per meter"},
    1237: {"symbol": "V/cm", "desc": "volt per centimeter"},
    1238: {"symbol": "mV/m", "desc": "millivolt per meter"},
    1239: {"symbol": "μV/m", "desc": "microvolt per meter"},
    1240: {"symbol": "V", "desc": "volt = 1 W/A"},
    1241: {"symbol": "MV", "desc": "megavolt = 106 V"},
    1242: {"symbol": "kV", "desc": "kilovolt = 103 V"},
    1243: {"symbol": "mV", "desc": "millivolt = 10-3 V"},
    1244: {"symbol": "μV", "desc": "microvolt = 10-6 V"},
    1245: {"symbol": "F", "desc": "farad = 1 C/V"},
    1246: {"symbol": "mF", "desc": "millifarad = 10-3 F"},
    1247: {"symbol": "μF", "desc": "microfarad = 10-6 F"},
    1248: {"symbol": "nF", "desc": "nanofarad = 10-9 F"},
    1249: {"symbol": "pF", "desc": "picofarad = 10-12 F"},
    1250: {"symbol": "F/m", "desc": "farad per meter"},
    1251: {"symbol": "μF/m", "desc": "microfarad per meter"},
    1252: {"symbol": "nF/m", "desc": "nanofarad per meter"},
    1253: {"symbol": "pF/m", "desc": "picofarad per meter"},
    1254: {"symbol": "C·m", "desc": "coulomb meter"},
    1255: {"symbol": "A/m2", "desc": "ampere per square meter"},
    1256: {"symbol": "MA/m2", "desc": "megaampere per square meter"},
    1257: {"symbol": "A/cm2", "desc": "ampere per square centimeter"},
    1258: {"symbol": "kA/m2", "desc": "kiloampere per square meter"},
    1259: {"symbol": "A/m", "desc": "ampere per meter"},
    1260: {"symbol": "kA/m", "desc": "kiloampere per meter"},
    1261: {"symbol": "A/cm", "desc": "ampere per centimeter"},
    1262: {"symbol": "T", "desc": "tesla = 1 Wb/m2"},
    1263: {"symbol": "mT", "desc": "millitesla = 10-3 T"},
    1264: {"symbol": "μT", "desc": "microtesla = 10-6 T"},
    1265: {"symbol": "nT", "desc": "nanotesla = 10-9 T"},
    1266: {"symbol": "Wb", "desc": "weber = 1 V·s"},
    1267: {"symbol": "mWb", "desc": "milliweber = 10-3 W"},
    1268: {"symbol": "Wb/m", "desc": "weber per meter"},
    1269: {"symbol": "kWb/m", "desc": "kiloweber per meter"},
    1270: {"symbol": "H", "desc": "henry = 1 Wb/A"},
    1271: {"symbol": "mH", "desc": "millihenry = 10-3 H"},
    1272: {"symbol": "μH", "desc": "microhenry = 10-6 H"},
    1273: {"symbol": "nH", "desc": "nanohenry = 10-9 H"},
    1274: {"symbol": "pH", "desc": "picohenry = 10-12 H"},
    1275: {"symbol": "H/m", "desc": "henry per meter"},
    1276: {"symbol": "μH/m", "desc": "microhenry per meter"},
    1277: {"symbol": "nH/m", "desc": "nanohenry per meter"},
    1278: {"symbol": "A·m2", "desc": "ampere square meter"},
    1279: {"symbol": "N·m2/A", "desc": "newton square meter per ampere"},
    1280: {"symbol": "Wb·m", "desc": "weber meter"},
    1281: {"symbol": "W", "desc": "ohm = 1 V/A"},
    1282: {"symbol": "GW", "desc": "gigaohm = 109 W"},
    1283: {"symbol": "MW", "desc": "megohm = 106 W"},
    1284: {"symbol": "kW", "desc": "kilohm = 103 W"},
    1285: {"symbol": "mW", "desc": "milliohm = 10-3 W"},
    1286: {"symbol": "μW", "desc": "microohm = 10-6 W"},
    1287: {"symbol": "S", "desc": "siemens = 1 W-1"},
    1288: {"symbol": "kS", "desc": "kilosiemens = 103 W-1"},
    1289: {"symbol": "mS", "desc": "millisiemens = 10-3 W-1"},
    1290: {"symbol": "μS", "desc": "microsiemens = 10-6 W-1"},
    1291: {"symbol": "W·m", "desc": "ohm meter"},
    1292: {"symbol": "GW·m", "desc": "gigaohm meter"},
    1293: {"symbol": "MW·m", "desc": "megohm meter"},
    1294: {"symbol": "kW·m", "desc": "kilohm meter"},
    1295: {"symbol": "W·cm", "desc": "ohm centimeter"},
    1296: {"symbol": "mW·m", "desc": "milliohm meter"},
    1297: {"symbol": "μW·m", "desc": "microohm meter"},
    1298: {"symbol": "nW·m", "desc": "nanoohm meter"},
    1299: {"symbol": "S/m", "desc": "siemens per meter"},
    1300: {"symbol": "MS/m", "desc": "megasiemens per meter"},
    1301: {"symbol": "kS/m", "desc": "kilosiemens per meter"},
    1302: {"symbol": "mS/cm", "desc": "millisiemens per centimeter"},
    1303: {"symbol": "μS/mm", "desc": "microsiemens per millimeter"},
    1304: {"symbol": "1/H", "desc": "per henry"},
    1305: {"symbol": "sr", "desc": "steradian = 1 m2/m2"},
    1306: {"symbol": "W/sr", "desc": "watt per steradian"},
    1307: {"symbol": "W/(sr·m2)", "desc": "watt per steradian square meter"},
    1308: {"symbol": "W/m2", "desc": "watt per square meter"},
    1309: {"symbol": "lm", "desc": "lumen = 1 cd·sr"},
    1310: {"symbol": "lm·s", "desc": "lumen second"},
    1311: {"symbol": "lm·h", "desc": "lumen hour"},
    1312: {"symbol": "lm/m2", "desc": "lumen per square meter"},
    1313: {"symbol": "lm/W", "desc": "lumen per watt"},
    1314: {"symbol": "lx", "desc": "lux = 1 lm/m2"},
    1315: {"symbol": "lx·s", "desc": "lux second"},
    1316: {"symbol": "cd", "desc": "candela SI"},
    1317: {"symbol": "cd/m2", "desc": "candela per square meter"},
    1318: {"symbol": "g/s", "desc": "gram per second"},
    1319: {"symbol": "g/min", "desc": "gram per minute"},
    1320: {"symbol": "g/h", "desc": "gram per hour"},
    1321: {"symbol": "g/d", "desc": "gram per day"},
    1322: {"symbol": "kg/s", "desc": "kilogram per second"},
    1323: {"symbol": "kg/min", "desc": "kilogram per minute"},
    1324: {"symbol": "kg/h", "desc": "kilogram per hour"},
    1325: {"symbol": "kg/d", "desc": "kilogram per day"},
    1326: {"symbol": "t/s", "desc": "metric ton per second"},
    1327: {"symbol": "t/min", "desc": "metric ton per minute"},
    1328: {"symbol": "t/h", "desc": "metric ton per hour"},
    1329: {"symbol": "t/d", "desc": "metric ton per day"},
    1330: {"symbol": "lb/s", "desc": "pound per second"},
    1331: {"symbol": "lb/min", "desc": "pound per minute"},
    1332: {"symbol": "lb/h", "desc": "pound per hour"},
    1333: {"symbol": "lb/d", "desc": "pound per day"},
    1334: {"symbol": "STon/s", "desc": "short ton per second"},
    1335: {"symbol": "STon/min", "desc": "short ton per minute"},
    1336: {"symbol": "STon/h", "desc": "short ton per hour"},
    1337: {"symbol": "STon/d", "desc": "short ton per day"},
    1338: {"symbol": "LTon/s", "desc": "long ton per second"},
    1339: {"symbol": "LTon/min", "desc": "long ton per minute"},
    1340: {"symbol": "LTon/h", "desc": "long ton per hour"},
    1341: {"symbol": "LTon/d", "desc": "long ton per day"},
    1342: {"symbol": "%", "desc": "percent = 0.01"},
    1343: {"symbol": "% sol/wt", "desc": "percent solid per weight"},
    1344: {"symbol": "% sol/vol", "desc": "percent solid per volume"},
    1345: {"symbol": "% stm qual", "desc": "percent steam quality"},
    1346: {"symbol": "°Plato", "desc": "degree Plato"},
    1347: {"symbol": "m3/s", "desc": "cubic meter per second"},
    1348: {"symbol": "m3/min", "desc": "cubic meter per minute"},
    1349: {"symbol": "m3/h", "desc": "cubic meter per hour"},
    1350: {"symbol": "m3/d", "desc": "cubic meter per day"},
    1351: {"symbol": "L/s", "desc": "liter per second"},
    1352: {"symbol": "L/min", "desc": "liter per minute"},
    1353: {"symbol": "L/h", "desc": "liter per hour"},
    1354: {"symbol": "L/d", "desc": "liter per day"},
    1355: {"symbol": "ML/d", "desc": "megaliter per day"},
    1356: {"symbol": "ft3/s", "desc": "cubic foot per second"},
    1357: {"symbol": "ft3/min", "desc": "cubic foot per minute"},
    1358: {"symbol": "ft3/h", "desc": "cubic foot per hour"},
    1359: {"symbol": "ft3/d", "desc": "cubic foot per day"},
    1360: {"symbol": "ft3/min std.", "desc": "standard cubic foot per minute"},
    1361: {"symbol": "ft3/h std.", "desc": "standard cubic foot per hour"},
    1362: {"symbol": "gal/s", "desc": "gallon (U.S.) per second"},
    1363: {"symbol": "gal/min", "desc": "gallon (U.S.) per minute"},
    1364: {"symbol": "gal/h", "desc": "gallon (U.S.) per hour"},
    1365: {"symbol": "gal/d", "desc": "gallon (U.S.) per day"},
    1366: {"symbol": "Mgal/d", "desc": "megagallon (U.S.) per day"},
    1367: {"symbol": "ImpGal/s", "desc": "gallon (Imperial) per second"},
    1368: {"symbol": "ImpGal/min", "desc": "gallon (Imperial) per minute"},
    1369: {"symbol": "ImpGal/h", "desc": "gallon (Imperial) per hour"},
    1370: {"symbol": "ImpGal/d", "desc": "gallon (Imperial) per day"},
    1371: {"symbol": "bbl/s", "desc": "barrel per second"},
    1372: {"symbol": "bbl/min", "desc": "barrel per minute"},
    1373: {"symbol": "bbl/h", "desc": "barrel per hour"},
    1374: {"symbol": "bbl/d", "desc": "barrel per day"},
    1375: {"symbol": "W/m2", "desc": "watt per square meter"},
    1376: {"symbol": "mW/m2", "desc": "milliwatt per square meter"},
    1377: {"symbol": "μW/m2", "desc": "microwatt per square meter"},
    1378: {"symbol": "pW/m2", "desc": "picowatt per square meter"},
    1379: {"symbol": "Pa·s/m3", "desc": "pascal second per cubic meter"},
    1380: {"symbol": "N·s/m", "desc": "newton second per meter"},
    1381: {"symbol": "Pa·s/m", "desc": "pascal second per meter"},
    1382: {"symbol": "B", "desc": "bel = lg(ratio)"},
    1383: {"symbol": "dB", "desc": "decibel = 10-1 B"},
    1384: {"symbol": "mol", "desc": "mole SI"},
    1385: {"symbol": "kmol", "desc": "kilomole"},
    1386: {"symbol": "mmol", "desc": "mill mole"},
    1387: {"symbol": "μmol", "desc": "micromole"},
    1388: {"symbol": "kg/mol", "desc": "kilogram per mole"},
    1389: {"symbol": "g/mol", "desc": "gram per mole"},
    1390: {"symbol": "m3/mol", "desc": "cubic meter per mole"},
    1391: {"symbol": "dm3/mol", "desc": "cubic decimeter per mole"},
    1392: {"symbol": "cm3/mol", "desc": "cubic centimeter per mole"},
    1393: {"symbol": "L/mol", "desc": "liter per mole"},
    1394: {"symbol": "J/mol", "desc": "joule per mole"},
    1395: {"symbol": "kJ/mol", "desc": "kilojoule per mole"},
    1396: {"symbol": "J/(mol-K)", "desc": "joule per mole kelvin"},
    1397: {"symbol": "mol/m3", "desc": "mole per cubic meter"},
    1398: {"symbol": "mol/dm3", "desc": "mole per cubic decimeter"},
    1399: {"symbol": "mol/L", "desc": "mole per liter"},
    1400: {"symbol": "mol/kg", "desc": "mole per kilogram"},
    1401: {"symbol": "mmol/kg", "desc": "millimole per kilogram"},
    1402: {"symbol": "Bq", "desc": "becquerel = 1 s-1"},
    1403: {"symbol": "MBq", "desc": "megabecquerel"},
    1404: {"symbol": "kBq", "desc": "kilobecquerel"},
    1405: {"symbol": "Bq/kg", "desc": "becquerel per kilogram"},
    1406: {"symbol": "kBq/kg", "desc": "kilobecquerel per kilogram"},
    1407: {"symbol": "MBq/kg", "desc": "megabecquerel per kilogram"},
    1408: {"symbol": "Gy", "desc": "gray = 1 J/kg"},
    1409: {"symbol": "mGy", "desc": "milligray"},
    1410: {"symbol": "rd", "desc": "rad = 10-2 Gy"},
    1411: {"symbol": "Sv", "desc": "sievert = 1 J/kg"},
    1412: {"symbol": "mSv", "desc": "millisievert"},
    1413: {"symbol": "rem", "desc": "rem = 10-2 Sv"},
    1414: {"symbol": "C/kg", "desc": "coulomb per kilogram"},
    1415: {"symbol": "mC/kg", "desc": "millicoulomb per kilogram"},
    1416: {"symbol": "R", "desc": "roentgen = 2.58·10-4 C/kg"},
    1417: {"symbol": "1/J·m3", "desc": ""},
    1418: {"symbol": "e/V·m3", "desc": ""},
    1419: {"symbol": "m3/C", "desc": "cubic meter per coulomb"},
    1420: {"symbol": "V/K", "desc": "volt per kelvin"},
    1421: {"symbol": "mV/K", "desc": "millivolt per kelvin"},
    1422: {"symbol": "pH", "desc": "pH"},
    1423: {"symbol": "ppm", "desc": "parts per million = 10-6"},
    1424: {"symbol": "ppb", "desc": "parts per billion = 10-9"},
    1425: {"symbol": "ppth", "desc": "parts per thousand = 10-3"},
    1426: {"symbol": "°Brix", "desc": "degree Brix"},
    1427: {"symbol": "°Ball", "desc": "degree Balling"},
    1428: {"symbol": "proof/vol", "desc": "proof per volume"},
    1429: {"symbol": "proof/mass", "desc": "proof per mass"},
    1430: {"symbol": "lb/ImpGal", "desc": "pound per gallon (Imperial)"},
    1431: {"symbol": "kcalth/s", "desc": "kilocalorie per second"},
    1432: {"symbol": "kcalth/min", "desc": "kilocalorie per minute"},
    1433: {"symbol": "kcalth/h", "desc": "kilocalorie per hour"},
    1434: {"symbol": "kcalth/d", "desc": "kilocalorie per day"},
    1435: {"symbol": "Mcalth/s", "desc": "megacalorie per second"},
    1436: {"symbol": "Mcalth/min", "desc": "megacalorie per minute"},
    1437: {"symbol": "Mcalth/d", "desc": "megacalorie per day"},
    1438: {"symbol": "kJ/s", "desc": "kilojoule per second"},
    1439: {"symbol": "kJ/min", "desc": "kilojoule per minute"},
    1440: {"symbol": "kJ/h", "desc": "kilojoule per hour"},
    1441: {"symbol": "kJ/d", "desc": "kilojoule per day"},
    1442: {"symbol": "MJ/s", "desc": "megajoule per second"},
    1443: {"symbol": "MJ/min", "desc": "megajoule per minute"},
    1444: {"symbol": "MJ/d", "desc": "megajoule per day"},
    1445: {"symbol": "Btu_th/s", "desc": "British thermal unit per second"},
    1446: {"symbol": "Btu_th/min", "desc": "British thermal unit per minute"},
    1447: {"symbol": "Btu_th/day", "desc": "British thermal unit per day"},
    1448: {"symbol": "μgal/s", "desc": "microgallon (U.S.) per second"},
    1449: {"symbol": "mgal/s", "desc": "milligallon (U.S.) per second"},
    1450: {"symbol": "kgal/s", "desc": "kilogallon (U.S.) per second"},
    1451: {"symbol": "Mgal/s", "desc": "megagallon (U.S.) per second"},
    1452: {"symbol": "μgal/min", "desc": "microgallon (U.S.) per minute"},
    1453: {"symbol": "mgal/min", "desc": "milligallon (U.S.) per second"},
    1454: {"symbol": "kgal/min", "desc": "kilogallon (U.S.) per minute"},
    1455: {"symbol": "Mgal/min", "desc": "megagallon (U.S.) per minute"},
    1456: {"symbol": "μgal/h", "desc": "microgallon (U.S.) per hour"},
    1457: {"symbol": "mgal/h", "desc": "milligallon (U.S.) per hour"},
    1458: {"symbol": "kgal/h", "desc": "kilogallon (U.S.) per hour"},
    1459: {"symbol": "Mgal/h", "desc": "megagallon (U.S.) per hour"},
    1460: {"symbol": "μgal/d", "desc": "microgallon (U.S.) per day"},
    1461: {"symbol": "mgal/d", "desc": "milligallon (U.S.) per day"},
    1462: {"symbol": "kgal/d", "desc": "kilogallon (U.S.) per day"},
    1463: {"symbol": "μImpGal/s", "desc": "microgallon (Imperial) per second"},
    1464: {"symbol": "mImpGal/s", "desc": "milligallon (Imperial) per second"},
    1465: {"symbol": "kImpGal/s", "desc": "kilogallon (Imperial) per second"},
    1466: {"symbol": "MImpGal/s", "desc": "megagallon (Imperial) per second"},
    1467: {"symbol": "μImpGal/min", "desc": "microgallon (Imperial) per minute"},
    1468: {"symbol": "mImpGal/min", "desc": "milligallon (Imperial) per minute"},
    1469: {"symbol": "kImpGal/min", "desc": "kilogallon (Imperial) per minute"},
    1470: {"symbol": "MImpGal/min", "desc": "megagallon (Imperial) per minute"},
    1471: {"symbol": "μImpGal/h", "desc": "microgallon (Imperial) per hour"},
    1472: {"symbol": "mImpGal/h", "desc": "milligallon (Imperial) per hour"},
    1473: {"symbol": "kImpGal/h", "desc": "kilogallon (Imperial) per hour"},
    1474: {"symbol": "MImpGal/h", "desc": "megagallon (Imperial) per hour"},
    1475: {"symbol": "μImpGal/d", "desc": "microgallon (Imperial) per day"},
    1476: {"symbol": "mImpGal/d", "desc": "milligallon (Imperial) per day"},
    1477: {"symbol": "kImpGal/d", "desc": "kilogallon (Imperial) per day"},
    1478: {"symbol": "MImpGal/d", "desc": "megagallon (Imperial) per day"},
    1479: {"symbol": "μbbl/s", "desc": "microbarrel per second"},
    1480: {"symbol": "mbbl/s", "desc": "millibarrel per second"},
    1481: {"symbol": "kbbl/s", "desc": "kilobarrel per second"},
    1482: {"symbol": "Mbbl/s", "desc": "megabarrel per second"},
    1483: {"symbol": "μbbl/min", "desc": "microbarrel per minute"},
    1484: {"symbol": "mbbl/min", "desc": "millibarrel per minute"},
    1485: {"symbol": "kbbl/min", "desc": "kilobarrel per minute"},
    1486: {"symbol": "Mbbl/min", "desc": "megabarrel per minute"},
    1487: {"symbol": "μbbl/h", "desc": "microbarrel per hour"},
    1488: {"symbol": "mbbl/h", "desc": "millibarrel per hour"},
    1489: {"symbol": "kbbl/h", "desc": "kilobarrel per hour"},
    1490: {"symbol": "Mbbl/h", "desc": "megabarrel per hour"},
    1491: {"symbol": "μbbl/d", "desc": "microbarrel per day"},
    1492: {"symbol": "mbbl/d", "desc": "millibarrel per day"},
    1493: {"symbol": "kbbl/d", "desc": "kilobarrel per day"},
    1494: {"symbol": "Mbbl/d", "desc": "megabarrel per day"},
    1495: {"symbol": "μm3/s", "desc": "cubic micrometer per second"},
    1496: {"symbol": "mm3/s", "desc": "cubic millimeter per second"},
    1497: {"symbol": "km3/s", "desc": "cubic kilometer per second"},
    1498: {"symbol": "Mm3/s", "desc": "cubic megameter per second"},
    1499: {"symbol": "μm3/min", "desc": "cubic micrometer per minute"},
    1500: {"symbol": "mm3/min", "desc": "cubic millimeter per minute"},
    1501: {"symbol": "km3/min", "desc": "cubic kilometer per minute"},
    1502: {"symbol": "Mm3/min", "desc": "cubic megameter per minute"},
    1503: {"symbol": "μm3/h", "desc": "cubic micrometer per hour"},
    1504: {"symbol": "mm3/h", "desc": "cubic millimeter per hour"},
    1505: {"symbol": "km3/h", "desc": "cubic kilometer per hour"},
    1506: {"symbol": "Mm3/h", "desc": "cubic megameter per hour"},
    1507: {"symbol": "μm3/d", "desc": "cubic micrometer per day"},
    1508: {"symbol": "mm3/d", "desc": "cubic millimeter per day"},
    1509: {"symbol": "km3/d", "desc": "cubic kilometer per day"},
    1510: {"symbol": "Mm3/d", "desc": "cubic megameter per day"},
    1511: {"symbol": "cm3/s", "desc": "cubic centimeter per second"},
    1512: {"symbol": "cm3/min", "desc": "cubic centimeter per minute"},
    1513: {"symbol": "cm3/h", "desc": "cubic centimeter per hour"},
    1514: {"symbol": "cm3/d", "desc": "cubic centimeter per day"},
    1515: {"symbol": "kcalth/kg", "desc": "kilocalorie per kilogram"},
    1516: {"symbol": "Btuth/lb", "desc": "British thermal unit per pound"},
    1517: {"symbol": "kL", "desc": "kiloliter"},
    1518: {"symbol": "kL/min", "desc": "kiloliter per minute"},
    1519: {"symbol": "kL/h", "desc": "kiloliter per hour"},
    1520: {"symbol": "kL/d", "desc": "kiloliter per day"},
    1521: {"symbol": "vendor-specific", "desc": ""},
    1522: {"symbol": "vendor-specific", "desc": ""},
    1523: {"symbol": "vendor-specific", "desc": ""},
    1524: {"symbol": "vendor-specific", "desc": ""},
    1525: {"symbol": "vendor-specific", "desc": ""},
    1526: {"symbol": "vendor-specific", "desc": ""},
    1527: {"symbol": "vendor-specific", "desc": ""},
    1528: {"symbol": "vendor-specific", "desc": ""},
    1529: {"symbol": "vendor-specific", "desc": ""},
    1530: {"symbol": "vendor-specific", "desc": ""},
    1531: {"symbol": "vendor-specific", "desc": ""},
    1532: {"symbol": "vendor-specific", "desc": ""},
    1533: {"symbol": "vendor-specific", "desc": ""},
    1534: {"symbol": "vendor-specific", "desc": ""},
    1535: {"symbol": "vendor-specific", "desc": ""},
    1536: {"symbol": "vendor-specific", "desc": ""},
    1537: {"symbol": "vendor-specific", "desc": ""},
    1538: {"symbol": "vendor-specific", "desc": ""},
    1539: {"symbol": "vendor-specific", "desc": ""},
    1540: {"symbol": "vendor-specific", "desc": ""},
    1541: {"symbol": "vendor-specific", "desc": ""},
    1542: {"symbol": "vendor-specific", "desc": ""},
    1543: {"symbol": "vendor-specific", "desc": ""},
    1544: {"symbol": "vendor-specific", "desc": ""},
    1545: {"symbol": "vendor-specific", "desc": ""},
    1546: {"symbol": "vendor-specific", "desc": ""},
    1547: {"symbol": "vendor-specific", "desc": ""},
    1548: {"symbol": "vendor-specific", "desc": ""},
    1549: {"symbol": "vendor-specific", "desc": ""},
    1550: {"symbol": "vendor-specific", "desc": ""},
    1551: {"symbol": "S/cm", "desc": "siemens per centimeter"},
    1552: {"symbol": "μS/cm", "desc": "microsiemens per centimeter"},
    1553: {"symbol": "mS/m", "desc": "millisiemens per meter"},
    1554: {"symbol": "μS/m", "desc": "microsiemens per meter"},
    1555: {"symbol": "MW·cm", "desc": "Megohm centimeter"},
    1556: {"symbol": "kW·cm", "desc": "kilohm centimeter"},
    1557: {"symbol": "Gew%", "desc": "Gewichtsprozent"},
    1558: {"symbol": "mg/L", "desc": "milligram per liter"},
    1559: {"symbol": "μg/L", "desc": "microgram per liter"},
    1560: {"symbol": "%Sät", "desc": ""},
    1561: {"symbol": "vpm", "desc": ""},
    1562: {"symbol": "%vol", "desc": "Volume percent"},
    1563: {"symbol": "ml/min", "desc": "milliliter per minute"},
    1564: {"symbol": "mg/dm3", "desc": "milligram per cubic decimeter"},
    1565: {"symbol": "mg/L", "desc": "milligram per liter (do not use in new projects; use 1558)"},
    1566: {"symbol": "mg/m3", "desc": "milligram per cubic meter"},
    1567: {"symbol": "ct", "desc": "carat (jewel) = 200.0·10-6 kg"},
    1568: {"symbol": "lb", "desc": "(tr) pound (troy or apothecary) = 0.3732417216 kg"},
    1569: {"symbol": "oz", "desc": "(tr) ounce (troy or apothecary) = 1/12 lb (tr)"},
    1570: {"symbol": "fl", "desc": "oz (U.S.) ounce (U.S. fluid) = (1/128) gal"},
    1571: {"symbol": "cm3", "desc": "cubic centimeter = 10-6 m3"},
    1572: {"symbol": "af", "desc": "acre foot = 43560 ft3"},
    1573: {"symbol": "m3 normal", "desc": "Normal cubic meter (0°C, 1atm = 101325Pa)"},
    1574: {"symbol": "L normal", "desc": "Normal liter (0°C, 1atm = 101325PA)"},
    1575: {"symbol": "m3 std.", "desc": "Standard cubic meter (20°C, 1atm = 101325Pa)"},
    1576: {"symbol": "L std.", "desc": "Standard liter (20°C, 1atm = 101325PA)"},
    1577: {"symbol": "ml/s", "desc": "milliliter per second"},
    1578: {"symbol": "ml/h", "desc": "milliliter per hour"},
    1579: {"symbol": "ml/d", "desc": "milliliter per day"},
    1580: {"symbol": "af/s", "desc": "acre foot per second"},
    1581: {"symbol": "af/min", "desc": "acre foot per minute"},
    1582: {"symbol": "af/h", "desc": "acre foot per hour"},
    1583: {"symbol": "af/d", "desc": "acre foot per day"},
    1584: {"symbol": "fl oz (U.S.)/s", "desc": "ounce (U.S. fluid) per second"},
    1585: {"symbol": "fl oz (U.S.)/min", "desc": "ounce (U.S. fluid) per minute"},
    1586: {"symbol": "fl oz (U.S.)/h", "desc": "ounce (U.S. fluid) per hour"},
    1587: {"symbol": "fl oz (U.S.)/d", "desc": "ounce (U.S. fluid) per day"},
    1588: {"symbol": "m3/s normal", "desc": "Normal cubic meter per second (0°C, 1atm = 101325Pa)"},
    1589: {"symbol": "m3/min normal", "desc": "Normal cubic meter per minute (0°C, 1atm = 101325Pa)"},
    1590: {"symbol": "m3/h normal", "desc": "Normal cubic meter per hour (0°C, 1atm = 101325Pa)"},
    1591: {"symbol": "m3/d normal", "desc": "Normal cubic meter per day (0°C, 1atm = 101325Pa)"},
    1592: {"symbol": "L/s normal", "desc": "Normal liter per second (0°C, 1atm = 101325PA)"},
    1593: {"symbol": "L/min normal", "desc": "Normal liter per minute (0°C, 1atm = 101325PA)"},
    1594: {"symbol": "L/h normal", "desc": "Normal liter per hour (0°C, 1atm = 101325PA)"},
    1595: {"symbol": "L/d normal", "desc": "Normal liter per day (0°C, 1atm = 101325PA)"},
    1596: {"symbol": "m3/s std.", "desc": "Standard cubic meter per second (20°C, 1atm = 101325Pa)"},
    1597: {"symbol": "m3/min std.", "desc": "Standard cubic meter per minute (20°C, 1atm = 101325Pa)"},
    1598: {"symbol": "m3/h std.", "desc": "Standard cubic meter per hour (20°C, 1atm = 101325Pa)"},
    1599: {"symbol": "m3/d std.", "desc": "Standard cubic meter per day (20°C, 1atm = 101325Pa)"},
    1600: {"symbol": "L/s std.", "desc": "Standard liter per second (20°C, 1atm = 101325PA)"},
    1601: {"symbol": "L/min std.", "desc": "Standard liter per minute (20°C, 1atm = 101325PA)"},
    1602: {"symbol": "L/h std.", "desc": "Standard liter per hour (20°C, 1atm = 101325PA)"},
    1603: {"symbol": "L/d std.", "desc": "Standard liter per day (20°C, 1atm = 101325PA)"},
    1604: {"symbol": "ft3/s std.", "desc": "standard cubic foot per second"},
    1605: {"symbol": "ft3/d std.", "desc": "standard cubic foot per day"},
    1606: {"symbol": "oz/s", "desc": "ounce per second"},
    1607: {"symbol": "oz/min", "desc": "ounce per minute"},
    1608: {"symbol": "oz/h", "desc": "ounce per hour"},
    1609: {"symbol": "oz/d", "desc": "ounce per day"},
    1610: {"symbol": "Pa_a", "desc": "pascal absolute"},
    1611: {"symbol": "Pa_g", "desc": "pascal gauge"},
    1612: {"symbol": "GPa_a", "desc": "gigapascal absolute"},
    1613: {"symbol": "GPa_g", "desc": "gigapascal gauge"},
    1614: {"symbol": "MPa_a", "desc": "megapascal absolute"},
    1615: {"symbol": "MPa_g", "desc": "megapascal gauge"},
    1616: {"symbol": "kPa_a", "desc": "kilopascal absolute"},
    1617: {"symbol": "kPa_g", "desc": "kilopascal gauge"},
    1618: {"symbol": "mPa_a", "desc": "millipascal absolute"},
    1619: {"symbol": "mPa_g", "desc": "millipascal gauge"},
    1620: {"symbol": "μPa_a", "desc": "micropascal absolute"},
    1621: {"symbol": "μPa_g", "desc": "micropascal gauge"},
    1622: {"symbol": "hPa_a", "desc": "hectopascal absolute"},
    1623: {"symbol": "hPa_g", "desc": "hectopascal gauge"},
    1624: {"symbol": "gf/cm2_a", "desc": "gram-force per square centimeter absolute"},
    1625: {"symbol": "gf/cm2_g", "desc": "gram-force per square centimeter gauge"},
    1626: {"symbol": "kgf/cm2_a", "desc": "kilogram-force per square centimeter absolute"},
    1627: {"symbol": "kgf/cm2_g", "desc": "kilogram-force per square centimeter gauge"},
    1628: {"symbol": "SD4°C", "desc": "standard density at 4°C"},
    1629: {"symbol": "SD15°C", "desc": "standard density at 15°C"},
    1630: {"symbol": "SD20°C", "desc": "standard density at 20°C"},
    1631: {"symbol": "PS", "desc": "metric horsepower (Pferdestärke) = 735.49875 W"},
    1632: {"symbol": "ppt", "desc": "parts per trillion = 10-12"},
    1633: {"symbol": "hl/s", "desc": "hectoliter per second"},
    1634: {"symbol": "hl/min", "desc": "hectoliter per minute"},
    1635: {"symbol": "hl/h", "desc": "hectoliter per hour"},
    1636: {"symbol": "hl/d", "desc": "hectoliter per day"},
    1637: {"symbol": "bbl (liq)/s", "desc": "barrel (U.S. liquid) per second"},
    1638: {"symbol": "bbl (liq)/min", "desc": "barrel (U.S. liquid) per minute"},
    1639: {"symbol": "bbl (liq)/h", "desc": "barrel (U.S. liquid) per hour"},
    1640: {"symbol": "bbl (liq)/d", "desc": "barrel (U.S. liquid) per day"},
    1641: {"symbol": "bbl (fed)", "desc": "barrel (U.S. federal) = 31 gal"},
    1642: {"symbol": "bbl (fed)/s", "desc": "barrel (U.S. federal) per second"},
    1643: {"symbol": "bbl (fed)/min", "desc": "barrel (U.S. federal) per minute"},
    1644: {"symbol": "bbl (fed)/h", "desc": "barrel (U.S. federal) per hour"},
    1645: {"symbol": "bbl (fed)/d", "desc": "barrel (U.S. federal) per day"},
    1646: {"symbol": "Reserved", "desc": ""},
    1995: {"symbol": "Textual unit definition", "desc": ""},
    1996: {"symbol": "Not used", "desc": ""},
    1997: {"symbol": "None", "desc": ""},
    1998: {"symbol": "unknown", "desc": ""},
    1999: {"symbol": "special", "desc": ""}
}
